[package]
name = "fw_client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ipnetwork = "0.20.0"
clap = { version = "4.0.9", features = ["derive"]}
neli = "0.6.2"
num_enum = "0.5.7"
